name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp
            TAG=${{ github.event.workflow_run.head_sha }}

            # Install Docker (Ubuntu 24.04 / noble)
            sudo apt-get update -y
            sudo apt-get install -y ca-certificates curl gnupg

            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg

            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              noble stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

            # Stop anything using port 8080
            PORT=8080
            if sudo lsof -i:$PORT -t >/dev/null ; then
              sudo kill -9 $(sudo lsof -i:$PORT -t)
            fi

            # Stop old container
            sudo docker stop myapp || true
            sudo docker rm myapp || true

            # Pull and run new image
            sudo docker pull $IMAGE:$TAG
            sudo docker run -d --name myapp -p 8080:80 $IMAGE:$TAG
